mydata <- read.csv("coursedata/household_power_consumption.txt", sep = ";", header=TRUE)
mydata$Date <- as.Date(mydata$Date, format = "%d/%m/%Y")
mydata$dat <- with(mydata, paste(mydata$Date, mydata$Time))
mydata$dat <- strptime(mydata$dat, "%Y-%m-%d %H:%M:%S")
date01 <- subset(mydata, mydata$Date == "2007-02-01")
date02 <- subset(mydata, mydata$Date == "2007-02-02")
df <- rbind(date01, date02)
df$Global_active_power <- as.numeric(as.character(df$Global_active_power))
df$Global_reactive_power <- as.numeric(as.character(df$Global_reactive_power))
df$Voltage <- as.numeric(as.character(df$Voltage))
df$Global_intensity <- as.numeric(as.character(df$Global_intensity))
df$Sub_metering_1 <- as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2 <- as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3 <- as.numeric(as.character(df$Sub_metering_3))


png(filename = "plot2.png")
plot(df$dat, df$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
dev.off()
